[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[language.formatter]
command = "prettier"
args = [ "--stdin-filepath", "a.ts" ]

[[language]]
name = "astro"
auto-format = true

[language.formatter]
command = "prettier"
args = [ "--stdin-filepath", "a.astro" ]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]

[language.formatter]
command = "prettier"
args = [ "--stdin-filepath", "a.tsx" ]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[language.formatter]
command = "prettier"
args = [ "--stdin-filepath", "a.js" ]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server"]

[language.formatter]
command = "prettier"
args = [ "--stdin-filepath", "a.jsx" ]
